# Generated by Django 3.0.5 on 2020-04-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coronadaily',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('dailyconfirmed', models.IntegerField()),
                ('dailydeceased', models.IntegerField()),
                ('dailyrecovered', models.IntegerField()),
                ('totalconfirmed', models.IntegerField()),
                ('totaldeceased', models.IntegerField()),
                ('totalrecovered', models.IntegerField()),
            ],
            options={
                'db_table': 'coronadaily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coronastatedaily',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('loc', models.CharField(max_length=50)),
                ('confirmedcasesforeign', models.IntegerField(db_column='confirmedCasesForeign')),
                ('confirmedcasesindian', models.IntegerField(db_column='confirmedCasesIndian')),
                ('deaths', models.IntegerField()),
                ('discharged', models.IntegerField()),
                ('totalconfirmed', models.IntegerField()),
            ],
            options={
                'db_table': 'coronastatedaily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coronaworld1',
            fields=[
                ('country_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('total_recovered', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('serious_critical', models.IntegerField()),
                ('active_cases', models.IntegerField()),
                ('total_cases_per_1m_population', models.IntegerField()),
                ('date', models.DateField()),
                ('deaths_per_1m_population', models.IntegerField(blank=True, null=True)),
                ('tests_per_1m_population', models.IntegerField(blank=True, null=True)),
                ('total_tests', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coronaworld1',
                'managed': False,
            },
        ),
    ]
