# Generated by Django 3.0.5 on 2020-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coronaworld1',
            fields=[
                ('country_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('total_recovered', models.IntegerField()),
                ('new_deaths', models.IntegerField()),
                ('new_cases', models.IntegerField()),
                ('serious_critical', models.IntegerField()),
                ('active_cases', models.IntegerField()),
                ('total_cases_per_1m_population', models.IntegerField()),
                ('date', models.DateField()),
                ('deaths_per_1m_population', models.IntegerField(blank=True, null=True)),
                ('tests_per_1m_population', models.IntegerField(blank=True, null=True)),
                ('total_tests', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coronaworld1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ImageField(upload_to='pics')),
                ('disc', models.CharField(max_length=15)),
            ],
        ),
    ]
